name: aind
channels:
- anaconda
- defaults
dependencies:
- pip
- cython=0.28.2
- matplotlib=2.1.1
- jupyter=1.0.0
- nltk=3.2.5
- nb_conda=2.2*
- pandas=0.22.0
- pomegranate=0.9.0
- pydot=1.2.4
- pydotplus=2.0.2
- python=3.5.4
- scikit-learn=0.19.1
- scipy=1.0.0
- tqdm=4.19.4
- pip:
  #  - jupyterlab=1.2.6
  - udacity-pa>=0.2
  - pygame==1.9.6
  - z3-solver
